#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,4,76,9,43,54,56,78&i=15,16,17,28,29,30,48,49&v=25,27,26,18,19,5,16,17 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* OneButton, RTCLib */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define L10N_LANGUAGE			RU
#define I2S_DOUT			25
#define I2S_BCLK			27
#define I2S_LRC			26

#define ENC_BTNR			18
#define ENC_BTNL			19
#define ENC_BTNB			5

//#define RTC_MODULE			DS1307
//#define RTC_SDA			16
//#define RTC_SCL			17

#define MAX_VOL	70


#endif


/*
MAX_VOL - программное ограничение громкости, подбирается вручную к колонкам и усилителю.
Чтобы оно заработало надо изменить файл: ..yoRadio\src\core\player.cpp

заменить строчку 298:  return vol;
на строчку:
return map(vol, 0, 254, 0, MAX_VOL + config.station.ovol);	//стало//
*/
